import json
from typing import List, Dict, Any, Tuple
from pydantic import BaseModel, Field


class EvidenceRecord(BaseModel):
    """
    Input schema for evidence records generated by the normalization stage.
    """
    evidence_id: str
    start_time_ms: int
    end_time_ms: int
    source_type: str  # "transcript", "ocr", "keyword"
    text: str


class ClipNode(BaseModel):
    """
    Output schema for the clip builder stage, to be ingested by semantic/graph modules.
    """
    clip_id: str
    video_id: str
    start_time_ms: int
    end_time_ms: int
    transcript_text: str
    ocr_text: str
    keywords: List[str]
    evidence_ids: List[str]


def parse_timestamp(ts: Any) -> int:
    """
    Parses a string timestamp into milliseconds.
    Supports formats like 'HH:MM:SS.mmm', 'MM:SS', 'SS.mmm', or raw numeric strings.
    Handles malformed or missing timestamps by returning 0.
    """
    if not ts:
        return 0
        
    ts_str = str(ts).strip().replace(',', '.')
    
    try:
        if ':' in ts_str:
            parts = ts_str.split(':')
            seconds = 0.0
            for part in parts:
                seconds = seconds * 60 + float(part)
            return int(seconds * 1000)
        else:
            return int(float(ts_str) * 1000)
    except (ValueError, TypeError):
        return 0


def assign_evidence_to_clip(
    clip_start_ms: int, 
    clip_end_ms: int, 
    sorted_evidence_records: List[EvidenceRecord]
) -> List[EvidenceRecord]:
    """
    Finds overlapping evidence for a given clip timeframe.
    Assumes `sorted_evidence_records` is sorted by `start_time_ms` ascending to avoid O(N^2).
    """
    matched_evidence: List[EvidenceRecord] = []
    
    for ev in sorted_evidence_records:
        # Since evidence is sorted by start_time_ms, if we reach an evidence
        # that starts after or exactly at the clip end, no further evidence will overlap.
        if ev.start_time_ms >= clip_end_ms:
            break
            
        # Overlap condition: start < clip.end AND end > clip.start
        if ev.end_time_ms > clip_start_ms:
            matched_evidence.append(ev)
            
    return matched_evidence


def aggregate_text_by_source(
    matched_evidence: List[EvidenceRecord]
) -> Tuple[str, str, List[str]]:
    """
    Aggregates text from matched evidence into transcript, ocr, and keywords.
    Maintains deterministic ordering based on the already sorted input.
    """
    transcripts: List[str] = []
    ocrs: List[str] = []
    keywords_list: List[str] = []
    seen_keywords: set = set()
    
    for ev in matched_evidence:
        if ev.source_type == "transcript":
            if ev.text:
                transcripts.append(ev.text.strip())
        elif ev.source_type == "ocr":
            if ev.text:
                ocrs.append(ev.text.strip())
        elif ev.source_type == "keyword":
            # Normalize to lowercase and deduplicate deterministically
            normalized_kw = ev.text.strip().lower()
            if normalized_kw and normalized_kw not in seen_keywords:
                seen_keywords.add(normalized_kw)
                keywords_list.append(normalized_kw)
                
    transcript_text = " ".join(transcripts)
    ocr_text = " ".join(ocrs)
    
    return transcript_text, ocr_text, keywords_list


def build_clips(
    rag_chunks: List[Dict[str, Any]], 
    evidence_records: List[EvidenceRecord]
) -> List[ClipNode]:
    """
    Builds ClipNode objects by defining clip boundaries from rag_chunks and 
    attaching overlapping EvidenceRecords.
    """
    if not rag_chunks:
        return []

    # Sort evidence once by start_time_ms for efficient matching (O(N log N))
    sorted_evidence = sorted(evidence_records, key=lambda x: x.start_time_ms)
    
    clips: List[ClipNode] = []
    
    for index, chunk in enumerate(rag_chunks):
        video_id = str(chunk.get("video_id", "unknown"))
        clip_id = f"{video_id}clip{index}"
        
        start_time_ms = parse_timestamp(chunk.get("start_time"))
        end_time_ms = parse_timestamp(chunk.get("end_time"))
        
        # Handle edge cases where end_time <= start_time
        if end_time_ms <= start_time_ms:
            end_time_ms = start_time_ms + 1000  # Give an arbitrary 1s window to avoid invalid states
            
        matched_evidence = assign_evidence_to_clip(
            clip_start_ms=start_time_ms,
            clip_end_ms=end_time_ms,
            sorted_evidence_records=sorted_evidence
        )
        
        transcript_text, ocr_text, keywords = aggregate_text_by_source(matched_evidence)
        
        # Ensure base keywords from rag_chunk are also included and deduplicated
        chunk_keywords = chunk.get("keywords", [])
        if isinstance(chunk_keywords, list):
            for kw in chunk_keywords:
                normalized_kw = str(kw).strip().lower()
                if normalized_kw and normalized_kw not in keywords:
                    keywords.append(normalized_kw)
                    
        # Extract evidence provenance
        evidence_ids = [ev.evidence_id for ev in matched_evidence]
        
        clip_node = ClipNode(
            clip_id=clip_id,
            video_id=video_id,
            start_time_ms=start_time_ms,
            end_time_ms=end_time_ms,
            transcript_text=transcript_text,
            ocr_text=ocr_text,
            keywords=keywords,
            evidence_ids=evidence_ids
        )
        
        clips.append(clip_node)
        
    return clips


if __name__ == "__main__":
    # 1. Mock rag_chunks
    mock_rag_chunks = [
        {
            "text": "Intro sequence.",
            "start_time": "00:00:00.000",
            "end_time": "00:00:10.500",
            "video_id": "vid123",
            "keywords": ["intro", "start"],
            "source": "manual"
        },
        {
            "text": "Main technical discussion.",
            "start_time": "00:00:10.000",
            "end_time": "00:00:25.000",
            "video_id": "vid123",
            "keywords": ["tech"],
            "source": "manual"
        },
        {
            "text": "Malformed chunk",
            "start_time": "invalid",
            "end_time": "00:00:30.000",
            "video_id": "vid123",
            "keywords": [],
            "source": "manual"
        }
    ]

    # 2. Mock EvidenceRecords
    mock_evidence = [
        EvidenceRecord(
            evidence_id="ev_t_1",
            start_time_ms=1000,
            end_time_ms=5000,
            source_type="transcript",
            text="Welcome to the video."
        ),
        EvidenceRecord(
            evidence_id="ev_k_1",
            start_time_ms=2000,
            end_time_ms=3000,
            source_type="keyword",
            text="Python"
        ),
        EvidenceRecord(
            evidence_id="ev_o_1",
            start_time_ms=10200,
            end_time_ms=15000,
            source_type="ocr",
            text="GraphRAG Architecture"
        ),
        EvidenceRecord(
            evidence_id="ev_t_2",
            start_time_ms=10400,
            end_time_ms=20000,
            source_type="transcript",
            text="Here we define the GraphRAG implementation."
        ),
        # This spans across both valid chunks
        EvidenceRecord(
            evidence_id="ev_o_2",
            start_time_ms=9000,
            end_time_ms=11000,
            source_type="ocr",
            text="Overlapping text"
        )
    ]

    # 3. Build Clips
    built_clips = build_clips(mock_rag_chunks, mock_evidence)

    # 4. Print Results
    for clip in built_clips:
        print(json.dumps(clip.model_dump(), indent=2))